num_workers: 4
pin_memory: false
drop_last: false
audio_locator: "|audio_features|"

train_ds:
  manifest_filepaths: "/home/khlu/lab/project_kira/training_set/train_manifest/0707_summarize.train.jsonl"
  data_root: "/home/khlu/nas/Datasets/DeSTA/PromptTTS"
  replace_keys: 
    - question
    - transcription
  chat_template:
    - role: user
      content: "|audio_features|{transcription}\n\n{question}"


  max_duration: 30
  min_duration: 0
  batch_size: 4 # per GPU
  shuffle: true
  num_samples: -1
  
  num_workers: ${dataset.num_workers}
  drop_last: ${dataset.drop_last}
  pin_memory: ${dataset.pin_memory}

validation_ds:
  manifest_filepaths: "/home/khlu/lab/project_kira/evaluation_set/eval_manifest/0707_core_combined.jsonl" # .json file
  data_root: "/livingrooms/khlu/Datasets/PromptTTS_dataset/test/target_16k"
  # manifest_filepaths: "/home/khlu/nas/Datasets/DeSTA/debug2.jsonl"
  # data_root: "/home/khlu/nas/Datasets/DeSTA"

  replace_keys: ${dataset.train_ds.replace_keys}
  chat_template: ${dataset.train_ds.chat_template}
  max_duration: ${dataset.train_ds.max_duration}
  min_duration: ${dataset.train_ds.min_duration}

  batch_size: 8 # per GPU
  shuffle: false
  num_samples: -1

  
  num_workers: ${dataset.num_workers}
  drop_last: ${dataset.drop_last}
  pin_memory: ${dataset.pin_memory}

test_ds:
  file: null # .json file
  batch_size: 24 # per GPU
  shuffle: false
  num_samples: -1
  
  # default values for the following params are retrieved from dataset config section, but you may override them
  num_workers: ${dataset.num_workers}
  drop_last: ${dataset.drop_last}
  pin_memory: ${dataset.pin_memory}